### ISSUE TITLE
How to compile pdfbooklet to exe in windows？

### ISSUE THREAD

**Issue by seuliang** [Averell7/PdfBooklet#13]
Is there guide to  compile pdfbooklet to exe in windows？

**Comment by Averell7** [comment]
To compile PdfBooklet to exe in windows, we use pyinstaller. 

1. The first step is to install the dependencies necessary to run Pdfbooklet from the py script (mainly PiGi-aio, and some others), 
2. Install pyinstaller (with pip, if I remember well)
3. run it with the command : pyinstaller -F pdfbooklet3.spec, using (and adapting) the spec file that I just added to the main directory.
