### ISSUE TITLE
PdfBooklet versus PdfBooklet2

### ISSUE THREAD

**Issue by Averell7** [Averell7/PdfBooklet#2]
There is on Github a project PdfBooklet2. It can be misleading because it is the version 2 of PdfBooklet, which development has been stopped in favour of the present version, 3.0. So PdfBooklet is more recent than PdfBooklet2. 

Major differences : 

| PdfBooklet2 | PdfBooklet |
| --- | --- |
| Python 2.7 | Python 3.4 |
| Gtk2 | Gtk3+ |
| PyPDF | PyPDF2 |

**Comment by bdheeman** [comment]
Just wrote a PKGBUILD for ArchLinux today, build using python2 (Python 2.7.14 (default, Sep 20 2017, 02:02:23), indeed) and installed 3.0.4, though About pages tells 3.0.3 :-(

**Strangely enough, it 3.0.4 somehow worked with python2 ;-)** 

I like and used pdfbooklet, it's really a nice tool, but un-maintained, poorly documented build and other dependencies.

_Moreover, I felt jealous on seeing that version 3.0.5 is released, but for windows only._

I'm not a python programmer, but i have lots of suggestions which I shall definitely discuss as soon as I see someone actively starts working on further development.

**Comment by bdheeman** [comment]
I think, the installer should not install PyPDF2, if a latest version is already installed.

**The idea of maintaining two separate code-bases PdfBooklet for python version 3 and PdfBooklet2 for version 2 is not good**. Hope, seasoned python programmers takeover it and make it portable and maintainable.

**Comment by Averell7** [comment]
Hello Balwinder,
    
    it is years now that we are asking for some Linux guy to help us
    build Linux packages. I am on Windows, and run Linux in VMWare,
    which is difficult with the firewall. The only really tested version
    on Linux is 2.4. That's why I maintained the code until now. 
    I have spent hours to try to find how to tell deb or rpm installers
    to install on Python 3, no result, and not found anything in Google.
    I abandoned the party, sorry. I am now manager of a company wich
    works in 9 countries, and although not a big company, it is a lot of
    work. 
    When soemone will have explained me how installing a software in
    Python 3, I will be able to delete version 2 which is no longer
    developed. I tried to write a code which is compatible with Python 2
    and Python 3. I think it is, and your experiment confirms that. But
    I would need more testing on real Linux platforms. 
    
    Presently I consider PdfBooklet as a maintained Windows application,
    and I tried to offer it to Linux users because I think there is no
    other software which can do the same work. But without the
    cooperation of at least a Linux developer, I can do nothing good. 
    
    3.0.5 adds a very specialised feature requested by a user. I have
    always a build of last versions (automatic on Travis). But I don't
    dare to make them public without any testing. If you want, I can add
    a "nightly builds" directory on SourceForge and put there the
    results. 
    
    Last version is always beta because I don't have a team of testers,
    but I use the program quite often, so I am sure it runs. 
    
    Best regards
    
    Dysmas
    
    Le 07/10/2017 21:24, Balwinder S
      Dheeman a écrit :
    
    
      Just wrote a PKGBUILD for ArchLinux today, build using python2
        (Python 2.7.14 (default, Sep 20 2017, 02:02:23), indeed) and
        installed 3.0.4, though About pages tells 3.0.3 :-(
      Strangely enough, it 3.0.4 somehow worked with python2
          ;-)
      I like and used pdfbooklet, it's really a nice tool, but
        un-maintained, poorly documented build and other dependencies.
      Moreover, I felt jealous on seeing that version 3.0.5 is
          released, but for windows only.
      I'm not a python programmer, but i have lots of suggestions
        which I shall definitely discuss as soon as I see someone
        actively starts working on further development.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Averell7/PdfBooklet","title":"Averell7/PdfBooklet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Averell7/PdfBooklet"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bdheeman in #2: Just wrote a PKGBUILD for ArchLinux today, build using python2 (Python 2.7.14 (default, Sep 20 2017, 02:02:23), indeed) and installed 3.0.4, though About pages tells 3.0.3 :-(\r\n\r\n**Strangely enough, it 3.0.4 somehow worked with python2 ;-)** \r\n\r\nI like and used pdfbooklet, it's really a nice tool, but un-maintained, poorly
 documented build and other dependencies.\r\n\r\n_Moreover, I felt jealous on seeing that version 3.0.5 is released, but for windows only._\r\n\r\nI'm not a python programmer, but i have lots of suggestions which I shall definitely discuss as soon as I see someone actively starts working on further development."}],"action":{"name":"View Issue","url":"https://github.com/Averell7/PdfBooklet/issues/2#issuecomment-334960022"}}}
    
    
   
	
      
		Garanti sans virus. www.avast.com
