### ISSUE TITLE
pdfshuffler_g3.py: 1040: SyntaxWarning: "is not" with a literal. Did you mean "!="?

### ISSUE THREAD

**Issue by Johann-Tree** [Averell7/PdfBooklet#22]
I get following error message when opening pdfbooklet on Ubuntu Linux 20.04.5:

```
/usr/lib/python3/dist-packages/pdfbooklet/pdfshuffler_g3.py:1040: SyntaxWarning: "is not" with a literal. Did you mean "!="?
 if rotate_times is not 0:
```

After editing /usr/lib/python3/dist-packages/pdfbooklet/pdfshuffler_g3.py with suggested change this message isn't shown anymore.

**Comment by Averell7** [comment]
Thanks for the bug report. Pdfshuffler is a third party program, no longer developed, but the author allowed us to integrate it inside PdfBooklet
