### ISSUE TITLE
Spanish translation is just French and English

### ISSUE THREAD

**Issue by cymerio** [Averell7/PdfBooklet#3]
When you open this program on a system configured with a Spanish locale, the strings shown are just a mix of English and French.
If you have a look at the files at "share/locale/es/LC_MESSAGES/*" there is not a single line in Spanish.

Deleting or renaming the "es" folder inside "share/locale" returns the program to English.

**Comment by Averell7** [comment]
You are right, thanks, we will clean that. 
If you want to make a Spanish translation, we will include it.
