### ISSUE TITLE
bad import statements, locally used modules are not in import path

### ISSUE THREAD

**Issue by UserXYZ** [Averell7/PdfBooklet#4]
Hello.

I tried to use pdfbooklet on my Fedora 26, but it's unusable because it fails to load any of the required modules from the pdfbooklet package itself.
I do not know how does that work in winblowz in the first place, but saying something like
`import PyPDF2_G` when PyPDF2_G is local module which has not been in any way linked into default python module search path, just won't work.
So, I had to rewrite all such import statements into something like
`import pdfbooklet.PyPDF2_G` in order to make it run.
I suspect that the author planned to have everything fixed in `/usr/local` folder and with some mumbo-jumbo `_import()` magic rewrite all the modules paths into global import path...but that won't work if the whole code is run from source folder or is installed in standard path, under `/usr`, which would be the case on every linux distro.
Testing it on Debian is not enough, it is vital to test on every major distro at least, and not to fix paths to anything in particular (except maybe config files under `/etc`).

In the end, I made a simple diff which may or may not be what is the right solution, but at least now the code works.

**Comment by Averell7** [comment]
Hello, 
    
    the author (me) is not a Linux guy. PdfBooklet was written in
    Windows. I just tried to make it compatible with Linux, and I am
    asking for years for someone to collaborate for the Linux versions,
    or at least tell me what I should do ! The /usr/local was for me a
    mystery, I have just seen that in my Ubuntu on a VMWare in Windows,
    the program was installed there, I don't have any idea of the
    reason.
    
    So thank you for the suggestions, and I will add them to the next
    version. Perhaps you could do a push request ? 
    
    
    
    Le 27/10/2017 11:24, Andrea Prunić a
      écrit :
    
    
      Hello.
      I tried to use pdfbooklet on my Fedora 26, but it's unusable
        because it fails to load any of the required modules from the
        pdfbooklet package itself.
        I do not know how does that work in winblowz in the first place,
        but saying something like
        import PyPDF2_G when PyPDF2_G is local module which
        has not been in any way linked into default python module search
        path, just won't work.
        So, I had to rewrite all such import statements into something
        like
        import pdfbooklet.PyPDF2_G in order to make it run.
        I suspect that the author planned to have everything fixed in /usr/local
        folder and with some mumbo-jumbo _import() magic
        rewrite all the modules paths into global import path...but that
        won't work if the whole code is run from source folder or is
        installed in standard path, under /usr, which
        would be the case on every linux distro.
        Testing it on Debian is not enough, it is vital to test on every
        major distro at least, and not to fix paths to anything in
        particular (except maybe config files under /etc).
      In the end, I made a simple diff which may or may not be what
        is the right solution, but at least now the code works.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it
          on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Averell7/PdfBooklet","title":"Averell7/PdfBooklet","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Averell7/PdfBooklet"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"bad import statements, locally use dmodules are not in import path (#4)"}],"action":{"name":"View Issue","url":"https://github.com/Averell7/PdfBooklet/issues/4"}}}
    
    
  



	
		
			
				
			
		
		
			
				L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
				www.avast.com

**Comment by UserXYZ** [comment]
Well, the program is compatible with linux, obviously, since I'm working in it.
The thing with /usr/local you got is most probably from the package creation/management that is used in Ubuntu, and should not be forced in any way unless you pass the installer a specific option.
That would be like forcing a windows game to be installed under `C:\Games` even though it should go under `C:\Program Files` or where ever the user wants, if he sets the path in the installer.

Now, the bigger problem is those import statements...under any platform and any version of python, they should not be like that.
By default, python installation uses a certain set of file-system paths as search paths for the modules which get imported in python code - for example `/usr/lib/python3.6/site-packages` is my system path.
Under it are the folders that represent module names, like `OpenSSL` or `pdfbooklet`.

Only this first level can be used for direct import statements, because python assumes that any *.py files in them are accessible with `import module` of `from module import`.

If you have subfolders beneath them, then they are not included in default module import paths, and any code from them should be imported as `import module.submodule` or `from module.submodule import`.

Since you have submodule PyPDF2_G within pdfbooklet module (subfolder in a folder) you have to use `import pdfbooklet.PyPDF2_G` in your code that is in pdfbooklet folder.
If you want to use code from another file in the same folder, you use `import .module` or `from .module import` where dot explicitely tells python to look only in that folder.
Similar to that, you could use `import ..module` which would import from a folder (module) one level up etc.

You could evade all of that if you would use something like `sys.path.append(os.path.abspath(os.path.dirname(__file__)))` at the beginning of the file you're trying to execute, which would append it's path to default module import path, thus giving you the chance to simply use `import file` and not think about where `file` really is.

And this all has to be done properly under any platform and any distribution, because python is supposed to be platform neutral - if you have appropriate modules (and versions), your code should work everywhere, regardless of where it is installed.

Unfortunatelly, I do not know how to make a push request since I am not really a developer and do not know much about git (I'm actually sysadmin that does development for my own, not-business related needs) since I do not collaborate with anybody on my own code...so, if you could tell me how to do it, I'd be happy to send you the diff file.

Cheers.

**Comment by Averell7** [comment]
I am not much familiar with Github myself, but I was able to do a pull request. Seems it worked.

**Comment by UserXYZ** [comment]
From my fork on github?
That's great, hope it helps, and I'll keep testing to see if there's something else that might be a problem.
