### ISSUE TITLE
extraneous *.mo files in FR locale

### ISSUE THREAD

**Issue by UserXYZ** [Averell7/PdfBooklet#5]
For some reason, *.mo files in FR locale dir from GDK, gettext, GTK etc are left and they collide with the system ones when you try to install pdfbooklet, especially if you make rpm/deb package.
Deleting them fixes the things.

BTW they did not exist in the previous versions of pdfbooklet, so it's obviously a minor mistake from developer, for which I also created a diff.

**Comment by Averell7** [comment]
They are needed for Windows versions, but it is better not to include them here, OK.

**Comment by UserXYZ** [comment]
They should be installed by the system installation of appropriate GTK etc packages, even under windows...if not, then something is wrong with windows packages and not pdfbooklet package.

**Comment by Averell7** [comment]
Gtk is not installed properly in Windows, so the only stable solution is to install a full Gtk with PdfBooklet, and used only by it.
