### ISSUE TITLE
pdfbooklet depende de python-gobject-cairo

### ISSUE THREAD

**Issue by xunorus** [Averell7/PdfBooklet#8]
HI, Im having trouble installing this amazing tool (pdfbooklet) in Linux Mint 18.3.
Im using pdfbooklet_3.0.5-2_all.deb file.

I get that pdfbooklet  needs python-gobject-cairo.

I tried sudo apt install python-gobject-cairo 
but its not in repositories.

any ideas?

**Comment by Averell7** [comment]
I hope the new versions fixed this problem. If not, tell us.
